backend:
  name: git-gateway
  branch: main

media_folder: "public/images"   # Where uploaded files are stored in your repo
public_folder: "/images"        # How those files are accessed in the site

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/home.yml"
        label: "Homepage"
        name: "home"
        fields:
          - { name: "title", label: "Hero Title", widget: "string" }
          - { name: "subtitle", label: "Hero Subtitle", widget: "string" }
          - { name: "hero_image", label: "Hero Image", widget: "image" }