<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Site Editor</title>
    <meta name="robots" content="noindex" />
  </head>
  <body>
    <!-- Netlify Identity widget (handles login, signup, reset password) -->
    <script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>

    <!-- Decap CMS (content manager) -->
    <script src="https://unpkg.com/decap-cms@^3.0.0/dist/decap-cms.js"></script>
  </body>
</html>