backend:
  name: github
  repo: SmurtazaAShah/SirQubairBhoot
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/home.yml"
        label: "Homepage"
        name: "home"
        fields:
          - { name: "title", label: "Hero Title", widget: "string" }
          - { name: "subtitle", label: "Hero Subtitle", widget: "string" }
          - { name: "hero_image", label: "Hero Image", widget: "image" }